vim.api.nvim_set_var("airline_powerline_fonts" , 1)
vim.api.nvim_set_var("airline_left_sep" ,'»')
vim.api.nvim_set_var("airline_left_sep" , '▶')
vim.api.nvim_set_var("airline_right_sep" , '«')
vim.api.nvim_set_var("airline_right_sep" , '◀')
vim.api.nvim_set_var("airline_symbols.linenr" , '␊')
vim.api.nvim_set_var("airline_symbols.linenr" , '␤')
vim.api.nvim_set_var("airline_symbols.linenr" , '¶')
vim.api.nvim_set_var("airline_symbols.branch" , '⎇')
vim.api.nvim_set_var("airline_symbols.paste" , 'ρ')
vim.api.nvim_set_var("airline_symbols.paste" , 'Þ')
vim.api.nvim_set_var("airline_symbols.paste" , '∥')
vim.api.nvim_set_var("airline_symbols.whitespace" , 'Ξ')

vim.api.nvim_set_var("airline_left_sep" , '')
vim.api.nvim_set_var("airline_left_alt_sep" , '')
vim.api.nvim_set_var("airline_right_sep" , '')
vim.api.nvim_set_var("airline_right_alt_sep" , '')
vim.api.nvim_set_var("airline_symbols.branch" , '')
vim.api.nvim_set_var("airline_symbols.readonly" , '')
vim.api.nvim_set_var("airline_symbols.linenr" , '')
vim.api.nvim_set_var("airline_theme" , 'base16')

